language: go
sudo: false

go:
    - 1.8

before_install:
  # Install Glide
  - mkdir -p "${GOPATH}/bin"
  - curl https://glide.sh/get | bash

  # Get deps
  - make get-deps

script:
  - make test
  - $GOPATH/bin/goveralls -service=travis-ci
